const PREFIX = 'md-reader__'
const p = ([block]: TemplateStringsArray) => PREFIX + block

export default {
  PREFIX,
  MD_BODY: p`body`,
  MD_SIDE: p`side`,
  MD_SIDE_ACTIVE: p`side-li--active`,
  MD_CONTENT: p`markdown-content`,
  MD_BUTTON: p`btn`,
  HEAD_ANCHOR: p`head-anchor`,
  BUTTON_WRAP_ELE: p`button-wrap`,
  CODE_TOGGLE_BTN: p`btn--code-toggle`,
  SIDE_EXPAND_BTN: p`btn--side-expand`,
  GO_TOP_BTN: p`btn--go-top`,
  COPY_BTN: p`btn--copy`,
  SIDE_COLLAPSED: 'side-collapsed',
  SIDE_EXPANDED: 'side-expanded',
  HAS_TABS: 'md-reader-has-tabs',
  SIDE_TABS: p`side-tabs`,
  SIDE_TAB: p`side-tab`,
  SIDE_TAB_ACTIVE: p`side-tab--active`,
  SIDE_SEARCH_BTN: p`side-search-btn`,
  SEARCH_BAR: p`search-bar`,
  SEARCH_INPUT: p`search-input`,
  SEARCH_CLOSE: p`search-close`,
  SEARCH_PANEL: p`search-panel`,
  SEARCH_GROUP_TITLE: p`search-group-title`,
  SEARCH_ITEM: p`search-item`,
  SEARCH_ITEM_HEADING: p`search-item--heading`,
  SEARCH_ITEM_CONTEXT: p`search-item--context`,
  SEARCH_HIT: p`search-hit`,
  SEARCH_MSG: p`search-msg`,
  SEARCH_FLASH: p`search-flash`,
  FILE_TREE: p`file-tree`,
  TREE_DIR: p`tree-dir`,
  TREE_DIR_OPEN: p`tree-dir--open`,
  TREE_FILE: p`tree-file`,
  TREE_FILE_ACTIVE: p`tree-file--active`,
  TREE_MSG: p`tree-msg`,
  TREE_FILTERED_HIDDEN: p`tree-filtered-hidden`,
  TREE_NAME_HIT: p`tree-name-hit`,
  TREE_FILTER_HINT: p`tree-filter-hint`,
  FILES_PANEL: p`files-panel`,
  FSA_PANEL: p`fsa-panel`,
  FSA_BUTTON: p`fsa-button`,
  FSA_HINT: p`fsa-hint`,
  MODAL: p`modal`,
  ZOOM_IMAGE: p`zoom-image`,
  CODE_WRAP: p`code-wrap`,
}
