const PREFIX = 'md-reader__'
const p = ([block]: TemplateStringsArray) => PREFIX + block

export default {
  PREFIX,
  MD_BODY: p`body`,
  MD_SIDE: p`side`,
  MD_SIDE_ACTIVE: p`side-li--active`,
  MD_CONTENT: p`markdown-content`,
  MD_BUTTON: p`btn`,
  HEAD_ANCHOR: p`head-anchor`,
  BUTTON_WRAP_ELE: p`button-wrap`,
  CODE_TOGGLE_BTN: p`btn--code-toggle`,
  SIDE_EXPAND_BTN: p`btn--side-expand`,
  GO_TOP_BTN: p`btn--go-top`,
  COPY_BTN: p`btn--copy`,
  SIDE_COLLAPSED: 'side-collapsed',
  SIDE_EXPANDED: 'side-expanded',
  SIDE_TABS: p`side-tabs`,
  SIDE_TAB: p`side-tab`,
  SIDE_TAB_ACTIVE: p`side-tab--active`,
  FILE_TREE: p`file-tree`,
  TREE_DIR: p`tree-dir`,
  TREE_DIR_OPEN: p`tree-dir--open`,
  TREE_FILE: p`tree-file`,
  TREE_FILE_ACTIVE: p`tree-file--active`,
  TREE_MSG: p`tree-msg`,
  MODAL: p`modal`,
  ZOOM_IMAGE: p`zoom-image`,
}
